---
# file: roles/docker-common/tasks/ip_addr.yaml
# Add each service to the /etc/hosts file

- name: "Build /etc/hosts file"
  lineinfile:
    path: /etc/hosts
    regexp: '.*{{ hostname }}$'
    line:  '{{ ip_addr }} {{ hostname }}'
    state: present
  vars:
    ip_addr: '{{ lookup("vars", item + "_ip_addr") }}'
    hostname: '{{ lookup("vars", item + "_hostname") }}'
  loop: "{{ services }}"
